import { GROUND, Pose, Pt, Skeleton, solve } from './pose'

/**
 * Turns a solved pose into drawable shapes.
 *
 * This is the single source of the figure's appearance. The React component maps the
 * shapes to SVG elements for the app; the render script maps them to an SVG string for
 * the contact sheets. Keeping the geometry here means the sheet you review is exactly
 * what the phone draws.
 *
 * The figure is built as smooth silhouettes rather than tubes joined at discs. Each body
 * part is one closed outline generated by walking its bone chain and offsetting a width
 * profile to either side, so an elbow bends as an elbow and a thigh has a shape. Three
 * things do most of the work in making it read as a person:
 *
 *   - A width profile per part, not a linear taper: deltoid at the shoulder, a biceps
 *     belly, a narrow elbow, a forearm belly, a narrow wrist. Same for the leg, where the
 *     calf bulge is what stops a shin looking like a stick.
 *   - Asymmetric front and back offsets on the torso, so in profile the chest carries
 *     forward and the seat carries back. A symmetric torso reads as a sausage whichever
 *     width you give it.
 *   - Clothing. A vest and shorts drawn over the body cost nothing and turn an abstract
 *     silhouette into a man dressed for training, which is most of the perceived realism.
 */

export type Shape =
  | { kind: 'path'; d: string }
  | { kind: 'circle'; c: Pt; r: number }

export type Role = 'skin' | 'vest' | 'shorts' | 'ground' | 'shadow'

export interface Layer {
  role: Role
  /** Drawn in the shaded palette: the side of the body away from the viewer. */
  far: boolean
  shapes: Shape[]
  opacity?: number
}

export type Facing = 'side' | 'front'

export interface GeometryOptions {
  /** Front-on exercises draw both chains lit and swap the head for a face-on oval. */
  facing?: Facing
}

// --- vector helpers -------------------------------------------------------------

const sub = (a: Pt, b: Pt): Pt => ({ x: a.x - b.x, y: a.y - b.y })
const add = (a: Pt, b: Pt): Pt => ({ x: a.x + b.x, y: a.y + b.y })
const mul = (a: Pt, k: number): Pt => ({ x: a.x * k, y: a.y * k })
const len = (a: Pt): number => Math.hypot(a.x, a.y) || 1e-6
const norm = (a: Pt): Pt => mul(a, 1 / len(a))
const perp = (a: Pt): Pt => ({ x: -a.y, y: a.x })
const dot = (a: Pt, b: Pt): number => a.x * b.x + a.y * b.y

/** A width profile entry: position along the chain, offset one way, offset the other. */
type Band = [t: number, front: number, back: number]

function bandAt(profile: Band[], t: number): [number, number] {
  if (t <= profile[0][0]) return [profile[0][1], profile[0][2]]
  for (let i = 1; i < profile.length; i++) {
    if (t <= profile[i][0]) {
      const [t0, f0, b0] = profile[i - 1]
      const [t1, f1, b1] = profile[i]
      const k = (t - t0) / (t1 - t0 || 1)
      // Smoothstep between bands so the silhouette has no visible corners.
      const e = k * k * (3 - 2 * k)
      return [f0 + (f1 - f0) * e, b0 + (b1 - b0) * e]
    }
  }
  const last = profile[profile.length - 1]
  return [last[1], last[2]]
}

/** Resample a polyline to `n` points spaced evenly by arc length. */
function resample(chain: Pt[], n: number): { p: Pt; tangent: Pt }[] {
  const segLen: number[] = []
  let total = 0
  for (let i = 1; i < chain.length; i++) {
    const l = len(sub(chain[i], chain[i - 1]))
    segLen.push(l)
    total += l
  }
  const out: { p: Pt; tangent: Pt }[] = []
  for (let i = 0; i < n; i++) {
    const target = (i / (n - 1)) * total
    let acc = 0
    let seg = 0
    while (seg < segLen.length - 1 && acc + segLen[seg] < target) {
      acc += segLen[seg]
      seg++
    }
    const k = segLen[seg] === 0 ? 0 : (target - acc) / segLen[seg]
    const a = chain[seg]
    const b = chain[seg + 1]
    out.push({ p: add(a, mul(sub(b, a), k)), tangent: norm(sub(b, a)) })
  }
  // Average neighbouring tangents so the normal turns smoothly through a bent joint
  // instead of flipping at the corner.
  return out.map((s, i) => {
    const prev = out[Math.max(0, i - 1)].tangent
    const next = out[Math.min(out.length - 1, i + 1)].tangent
    return { p: s.p, tangent: norm({ x: prev.x + s.tangent.x + next.x, y: prev.y + s.tangent.y + next.y }) }
  })
}

/** Closed smooth path through points, Catmull-Rom converted to cubic beziers. */
function closedPath(pts: Pt[]): string {
  const n = pts.length
  const at = (i: number) => pts[(i + n) % n]
  let d = `M${at(0).x.toFixed(2)},${at(0).y.toFixed(2)}`
  for (let i = 0; i < n; i++) {
    const p0 = at(i - 1)
    const p1 = at(i)
    const p2 = at(i + 1)
    const p3 = at(i + 2)
    const c1 = { x: p1.x + (p2.x - p0.x) / 6, y: p1.y + (p2.y - p0.y) / 6 }
    const c2 = { x: p2.x - (p3.x - p1.x) / 6, y: p2.y - (p3.y - p1.y) / 6 }
    d += `C${c1.x.toFixed(2)},${c1.y.toFixed(2)} ${c2.x.toFixed(2)},${c2.y.toFixed(2)} ${p2.x.toFixed(2)},${p2.y.toFixed(2)}`
  }
  return `${d}Z`
}

/**
 * A limb or torso: walk the bone chain, offset the width profile to either side, and
 * close the outline with rounded caps.
 *
 * `frontDir`, when given, fixes which side of the chain the `front` half of the profile
 * falls on. The torso needs it so the chest stays on the chest side however the body
 * leans; limbs are near enough symmetric not to care.
 */
function ribbon(
  chain: Pt[],
  profile: Band[],
  opts: { samples?: number; frontDir?: Pt; capStart?: boolean; capEnd?: boolean; range?: [number, number]; inflate?: number } = {},
): Shape {
  const samples = opts.samples ?? 22
  const inflate = opts.inflate ?? 0
  const [t0, t1] = opts.range ?? [0, 1]
  const pts = resample(chain, samples)

  const left: Pt[] = []
  const right: Pt[] = []
  for (let i = 0; i < pts.length; i++) {
    const t = i / (pts.length - 1)
    if (t < t0 - 1e-6 || t > t1 + 1e-6) continue
    const [f, b] = bandAt(profile, t)
    let n = perp(pts[i].tangent)
    if (opts.frontDir && dot(n, opts.frontDir) < 0) n = mul(n, -1)
    left.push(add(pts[i].p, mul(n, f + inflate)))
    right.push(add(pts[i].p, mul(n, -(b + inflate))))
  }

  const first = pts[Math.round(t0 * (pts.length - 1))]
  const last = pts[Math.round(t1 * (pts.length - 1))]
  const cap = (s: { p: Pt; tangent: Pt }, out: boolean, wf: number, wb: number): Pt[] => {
    let n = perp(s.tangent)
    if (opts.frontDir && dot(n, opts.frontDir) < 0) n = mul(n, -1)
    const dir = mul(s.tangent, out ? 1 : -1)
    const r = (wf + wb) / 2
    // Three points are enough of an arc once the whole outline is smoothed.
    return [
      add(add(s.p, mul(n, out ? wf * 0.75 : -wb * 0.75)), mul(dir, r * 0.6)),
      add(s.p, mul(dir, r * 0.95)),
      add(add(s.p, mul(n, out ? -wb * 0.75 : wf * 0.75)), mul(dir, r * 0.6)),
    ]
  }

  const [fEnd, bEnd] = bandAt(profile, t1)
  const [fStart, bStart] = bandAt(profile, t0)
  const outline = [
    ...left,
    ...(opts.capEnd === false ? [] : cap(last, true, fEnd + inflate, bEnd + inflate)),
    ...right.reverse(),
    ...(opts.capStart === false ? [] : cap(first, false, fStart + inflate, bStart + inflate)),
  ]
  return { kind: 'path', d: closedPath(outline) }
}

// --- width profiles -------------------------------------------------------------

/**
 * Torso, pelvis to neck base. Side view carries the chest forward and the seat back;
 * front view is symmetric and much wider at the shoulders.
 */
const TORSO_SIDE: Band[] = [
  [0.0, 4.6, 6.0],
  [0.22, 4.3, 4.9],
  [0.45, 4.9, 4.7],
  [0.72, 6.0, 5.1],
  [1.0, 4.6, 5.0],
]
const TORSO_FRONT: Band[] = [
  [0.0, 6.0, 6.0],
  [0.28, 5.1, 5.1],
  [0.55, 6.4, 6.4],
  [0.85, 8.2, 8.2],
  [1.0, 8.4, 8.4],
]

/** Shoulder to hand. The bulges are what separate an arm from a stick. */
const ARM: Band[] = [
  [0.0, 3.9, 3.9],
  [0.16, 3.5, 3.5],
  [0.42, 2.6, 2.6],
  [0.52, 2.5, 2.5],
  [0.68, 2.8, 2.8],
  [0.88, 1.8, 1.8],
  [1.0, 1.7, 1.7],
]

/** Hip to ankle: glute, thigh, narrow knee, calf belly, narrow ankle. */
const LEG: Band[] = [
  [0.0, 5.0, 5.0],
  [0.18, 4.6, 4.6],
  [0.44, 3.3, 3.3],
  [0.52, 3.1, 3.1],
  [0.68, 3.6, 3.6],
  [0.9, 2.1, 2.1],
  [1.0, 1.9, 1.9],
]

const NECK: Band[] = [
  [0.0, 2.9, 3.1],
  [1.0, 2.5, 2.7],
]

/**
 * Head in profile, as offsets from the head centre in (front, up): skull, brow, nose,
 * lips, chin, jaw. The nose and chin are what make a leaning figure legible, because
 * they say which way it is looking.
 */
const HEAD_SCALE = 1.2
const HEAD_SIDE: [number, number][] = ([
  [0.0, 4.4], [1.9, 4.1], [3.2, 2.6], [3.1, 1.4], [4.3, 0.2], [3.2, -0.7],
  [3.4, -1.7], [2.7, -2.9], [1.2, -3.8], [-0.9, -4.0], [-2.6, -3.1],
  [-4.0, -1.4], [-4.5, 0.5], [-4.1, 2.3], [-2.7, 3.8], [-1.3, 4.4],
] as [number, number][]).map(([f, u]) => [f * HEAD_SCALE, u * HEAD_SCALE] as [number, number])

/** Head face-on: a plain oval, since there is no profile to show. */
const HEAD_FRONT: [number, number][] = Array.from({ length: 16 }, (_, i) => {
  const a = (i / 16) * Math.PI * 2
  return [Math.sin(a) * 3.9 * HEAD_SCALE, Math.cos(a) * 4.6 * HEAD_SCALE]
})

// --- assembly -------------------------------------------------------------------

/** Where an arm or leg visually leaves the body, face-on. The rig hangs both from one
 *  point; drawing them from the shoulder and hip instead stops them sprouting from the
 *  neck. Horizontal only, so ground contacts keep their height. */
const FRONT_SHOULDER_OFFSET = 4.6
const FRONT_HIP_OFFSET = 2.9

function headShape(s: Skeleton, facing: Facing): Shape {
  const up = s.up
  const front = s.front
  const outline = facing === 'side' ? HEAD_SIDE : HEAD_FRONT
  // Sit the head slightly down its own axis so the jaw meets the neck.
  const centre = add(s.head, mul(up, -0.8))
  const pts = outline.map(([f, u]) => add(add(centre, mul(front, f)), mul(up, u)))
  return { kind: 'path', d: closedPath(pts) }
}

function armChain(s: Skeleton, side: 'L' | 'R', dx: number): Pt[] {
  const shift = (p: Pt) => ({ x: p.x + dx, y: p.y })
  return side === 'L'
    ? [shift(s.neck), shift(s.elbowL), shift(s.handL)]
    : [shift(s.neck), shift(s.elbowR), shift(s.handR)]
}

function legChain(s: Skeleton, side: 'L' | 'R', dx: number): Pt[] {
  const shift = (p: Pt) => ({ x: p.x + dx, y: p.y })
  return side === 'L'
    ? [shift(s.pelvis), shift(s.kneeL), shift(s.ankleL)]
    : [shift(s.pelvis), shift(s.kneeR), shift(s.ankleR)]
}

function footShape(s: Skeleton, side: 'L' | 'R', dx: number): Shape {
  const ankle = side === 'L' ? s.ankleL : s.ankleR
  const toe = side === 'L' ? s.toeL : s.toeR
  const a = { x: ankle.x + dx, y: ankle.y }
  const t = { x: toe.x + dx, y: toe.y }
  const dir = norm(sub(t, a))
  const n = perp(dir)
  const heel = sub(a, mul(dir, 2.0))
  const pts = [
    add(heel, mul(n, 1.9)),
    add(add(a, mul(dir, 1.5)), mul(n, 1.7)),
    add(t, mul(n, 1.1)),
    add(add(t, mul(dir, 0.9)), mul(n, 0.2)),
    add(t, mul(n, -1.0)),
    add(a, mul(n, -1.9)),
    add(heel, mul(n, -2.0)),
  ]
  return { kind: 'path', d: closedPath(pts) }
}

/** Polygon approximation of an ellipse, for the ground shadow. */
function ellipse(cx: number, cy: number, rx: number, ry: number, n = 20): Pt[] {
  const pts: Pt[] = []
  for (let i = 0; i < n; i++) {
    const a = (i / n) * Math.PI * 2
    pts.push({ x: cx + Math.cos(a) * rx, y: cy + Math.sin(a) * ry })
  }
  return pts
}

export interface Geometry {
  layers: Layer[]
  skeleton: Skeleton
}

export function buildGeometry(pose: Pose, opts: GeometryOptions = {}): Geometry {
  const facing = opts.facing ?? 'side'
  const s = solve(pose)
  const front = facing === 'front'

  const torsoChain = [s.pelvis, s.chest, s.neck]
  const torsoProfile = front ? TORSO_FRONT : TORSO_SIDE

  const limb = (side: 'L' | 'R', dx: number) => {
    const arm = armChain(s, side, dx)
    const leg = legChain(s, side, dx)
    return {
      arm: ribbon(arm, ARM, { samples: 20 }),
      leg: ribbon(leg, LEG, { samples: 20 }),
      foot: footShape(s, side, dx),
      // Shorts stop mid-thigh; the vest hem overlaps them at the waist.
      shorts: ribbon(leg, LEG, { samples: 20, range: [0, 0.34], inflate: 0.55, capEnd: false }),
    }
  }

  const nearDx = front ? FRONT_SHOULDER_OFFSET : 0
  const near = limb('R', 0)
  const far = limb('L', 0)
  if (front) {
    // Face-on, the chains are redrawn from the shoulder and hip rather than the midline.
    near.arm = ribbon(armChain(s, 'R', nearDx), ARM, { samples: 20 })
    far.arm = ribbon(armChain(s, 'L', -nearDx), ARM, { samples: 20 })
    near.leg = ribbon(legChain(s, 'R', FRONT_HIP_OFFSET), LEG, { samples: 20 })
    far.leg = ribbon(legChain(s, 'L', -FRONT_HIP_OFFSET), LEG, { samples: 20 })
    near.foot = footShape(s, 'R', FRONT_HIP_OFFSET)
    far.foot = footShape(s, 'L', -FRONT_HIP_OFFSET)
    near.shorts = ribbon(legChain(s, 'R', FRONT_HIP_OFFSET), LEG, { samples: 20, range: [0, 0.34], inflate: 0.55, capEnd: false })
    far.shorts = ribbon(legChain(s, 'L', -FRONT_HIP_OFFSET), LEG, { samples: 20, range: [0, 0.34], inflate: 0.55, capEnd: false })
  }

  const lowest = Math.max(s.toeL.y, s.toeR.y, s.handL.y, s.handR.y, s.pelvis.y)
  const spanX =
    Math.max(s.head.x, s.toeL.x, s.toeR.x, s.handL.x, s.handR.x) -
    Math.min(s.head.x, s.toeL.x, s.toeR.x, s.handL.x, s.handR.x)
  const centreX = (s.pelvis.x + s.neck.x) / 2

  const layers: Layer[] = [
    {
      role: 'ground',
      far: false,
      shapes: [
        {
          kind: 'path',
          d: closedPath([
            { x: 4, y: GROUND + 1.4 },
            { x: 96, y: GROUND + 1.4 },
            { x: 96, y: GROUND + 2.5 },
            { x: 4, y: GROUND + 2.5 },
          ]),
        },
      ],
    },
    {
      role: 'shadow',
      far: false,
      shapes: [{ kind: 'path', d: closedPath(ellipse(centreX, GROUND + 2, Math.max(10, spanX * 0.42), 2.6)) }],
      opacity: Math.max(0.1, 0.45 - (GROUND - lowest) / 60),
    },

    // Far side first, then the body, then the near side.
    { role: 'skin', far: true, shapes: [far.leg, far.foot] },
    { role: 'shorts', far: true, shapes: [far.shorts] },
    { role: 'skin', far: true, shapes: [far.arm] },

    {
      role: 'skin',
      far: false,
      shapes: [
        ribbon([s.neck, add(s.neck, mul(s.up, 5))], NECK, { samples: 6, frontDir: s.front }),
        ribbon(torsoChain, torsoProfile, { samples: 24, frontDir: s.front }),
        headShape(s, facing),
      ],
    },
    {
      role: 'vest',
      far: false,
      shapes: [ribbon(torsoChain, torsoProfile, { samples: 24, frontDir: s.front, range: [0.04, 0.84], inflate: 0.5, capEnd: false })],
    },

    { role: 'skin', far: false, shapes: [near.leg, near.foot] },
    {
      role: 'shorts',
      far: false,
      // The waistband is part of the torso, not the legs, so it laps over the vest hem
      // and the two garments meet.
      shapes: [
        ribbon(torsoChain, torsoProfile, { samples: 24, frontDir: s.front, range: [0, 0.3], inflate: 0.65, capEnd: false }),
        near.shorts,
      ],
    },
    { role: 'skin', far: false, shapes: [near.arm] },
  ]

  return { layers, skeleton: s }
}

/** Serialise a point list for SVG. Kept for callers that still draw polygons. */
export function polyPoints(pts: Pt[]): string {
  return pts.map((p) => `${p.x.toFixed(2)},${p.y.toFixed(2)}`).join(' ')
}
